language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

script: travis_wait 60 julia --code-coverage -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); Pkg.add("Coverage")'
  - julia -e 'import BufferedStreams; cd(dirname(dirname(pathof(BufferedStreams)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import BufferedStreams; cd(dirname(dirname(pathof(BufferedStreams)))); Codecov.submit(process_folder())'
