language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("BufferedStreams")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(joinpath(Pkg.dir("BufferedStreams"), "docs/src")); mkdir("assets"); cd("assets"); run(pipeline(`curl https://codeload.github.com/BioJulia/assets/tar.gz/master`, `tar -xz --strip=2 assets-master/doc_assets`))'
  - julia --color=yes -e 'cd(Pkg.dir("BufferedStreams")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
